Fix non-union op raise ERROR when none of column is hashable. (#17614)
Before this PR, the following SQL will raise an ERROR
postgres=# create table base_type_t(a int, b int) distributed by (a);
postgres=# create table test_non_hashable(distkey base_type_t);
postgres=# explain (costs off)
postgres-# select * from test_non_hashable intersect select * from test_non_hashable;
ERROR:  unexpected gang size: 3 (nodeMotion.c:732)

The reason is that in the adjust_setop_arguments() if the setop is partitioned,
the make_motion_hash_all_targets() will change the locus to singleQE when none of the columns is hashable.
But mark_append_locus() will change it back to the original partitioned locus, generating a wrong plan.

This PR adds the check in choose_setop_type when none of column is hashable.